export const ADMIN_CONFIG = {
  DASHBOARD_CACHE_TTL: 300, // 5 minutes
  AUDIT_RETENTION_DAYS: 365,
  MAX_IMPERSONATION_DURATION_HOURS: 4,
  WEBHOOK_MAX_RETRIES: 5,
  WEBHOOK_BACKOFF_BASE_SECONDS: 10,
};
