export const ROUTING_KEYS = {
  EMAIL_VERIFICATION: 'email.verification',
  EMAIL_WELCOME: 'email.welcome',
  EMAIL_PASSWORD_RESET: 'email.password-reset',
  EMAIL_QUOTE_SENT: 'email.quote-sent',
  EMAIL_PAYMENT_RECEIPT: 'email.payment-receipt',
  EMAIL_CONTACT_RESPONSE: 'email.contact-response',
  NOTIFICATION_NEW: 'notification.new',
  NOTIFICATION_BATCH: 'notification.batch',
  AUDIT_LOG: 'audit.log',
  MEDIA_PROCESS: 'media.process',
  MEDIA_THUMBNAIL: 'media.thumbnail',
  ANALYTICS_EVENT: 'analytics.event',
  WEBHOOK_OUTBOUND: 'webhook.outbound',
  CDN_INVALIDATE: 'cdn.invalidate',
  PAYMENT_COMPLETED: 'payment.completed',
  PAYMENT_FAILED: 'payment.failed',
  PROJECT_STATUS_CHANGED: 'project.status-changed',
} as const;
