import { normalizeOpenApiDocument } from './normalize-openapi';

/**
 * Merges multiple OpenAPI 3.x documents into a single spec (paths + components).
 */

export interface OpenApiDocument {
  openapi?: string;
  info?: Record<string, unknown>;
  paths?: Record<string, Record<string, unknown>>;
  tags?: Array<{ name: string; description?: string }>;
  servers?: Array<Record<string, unknown>>;
  components?: {
    schemas?: Record<string, unknown>;
    securitySchemes?: Record<string, unknown>;
    parameters?: Record<string, unknown>;
    responses?: Record<string, unknown>;
  };
  security?: unknown[];
}

export interface OpenApiSpecSource {
  name: string;
  serviceKey: string;
  document: OpenApiDocument;
}

export interface MergeOpenApiResult {
  document: OpenApiDocument;
  /** Duplicate path/method keys skipped after the first service (first wins). */
  duplicatePaths: Array<{
    path: string;
    method?: string;
    keptFrom: string;
    skippedFrom: string;
  }>;
}

const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete', 'options', 'head', 'trace'];

/**
 * Microservice paths that duplicate gateway-canonical URLs (prefer gateway document).
 * Example: public blog is `/api/v1/blog/posts` on the gateway, not `/api/v1/posts`.
 */
const MICROSERVICE_PATH_EXCLUDE: Record<string, RegExp[]> = {
  blog: [
    /^\/api\/v1\/posts(\/|$)/,
    /^\/api\/v1\/categories(\/|$)/,
    /^\/api\/v1\/tags(\/|$)/,
    /^\/api\/v1\/authors(\/|$)/,
    /^\/api\/v1\/feed(\/|$)/,
    /^\/api\/v1\/bookmarks(\/|$)/,
  ],
  /** Gateway admin module is canonical for `/api/v1/admin/*`. */
  progress: [/^\/api\/v1\/admin\//, /^\/api\/v1\/projects\/\{projectId\}\/progress/],
  projects: [/^\/api\/v1\/admin\//, /^\/api\/v1\/projects\/\{id\}\/progress$/],
  payments: [/^\/api\/v1\/admin\/milestones\//],
  portfolio: [/^\/api\/v1\/admin\//],
  /** Gateway webhooks module is canonical (avoids `{provider}` vs `{id}` template clash). */
  webhooks: [/^\/api\/v1\/webhooks(\/|$)/],
};

/** Internal microservice OpenAPI paths fully covered by gateway proxy routes. */
const MICROSERVICE_EXCLUDE_ALL = new Set(['admin']);

function shouldIncludeMicroservicePath(serviceKey: string, path: string): boolean {
  if (MICROSERVICE_EXCLUDE_ALL.has(serviceKey)) return false;
  const patterns = MICROSERVICE_PATH_EXCLUDE[serviceKey];
  if (!patterns?.length) return true;
  return !patterns.some((pattern) => pattern.test(path));
}

function prefixOperationIds(
  pathItem: Record<string, unknown>,
  serviceKey: string,
): Record<string, unknown> {
  const methods = ['get', 'post', 'put', 'patch', 'delete', 'options', 'head', 'trace'];
  const result = { ...pathItem };

  for (const method of methods) {
    const operation = result[method];
    if (operation && typeof operation === 'object' && !Array.isArray(operation)) {
      const op = { ...(operation as Record<string, unknown>) };
      if (typeof op.operationId === 'string' && !op.operationId.startsWith(`${serviceKey}_`)) {
        op.operationId = `${serviceKey}_${op.operationId}`;
      }
      result[method] = op;
    }
  }

  return result;
}

type SchemaRenameMap = Map<string, string>;

function mergeComponentSection(
  target: Record<string, unknown>,
  source: Record<string, unknown> | undefined,
  serviceKey: string,
  renames: SchemaRenameMap,
): void {
  if (!source) return;

  for (const [key, value] of Object.entries(source)) {
    if (!(key in target)) {
      target[key] = value;
      continue;
    }
    const namespacedKey = `${serviceKey}_${key}`;
    target[namespacedKey] = value;
    renames.set(key, namespacedKey);
  }
}

const REF_PREFIX = '#/components/schemas/';

function rewriteSchemaRefs(node: unknown, renames: SchemaRenameMap): void {
  if (!node || typeof node !== 'object') return;

  if (Array.isArray(node)) {
    for (const item of node) rewriteSchemaRefs(item, renames);
    return;
  }

  const record = node as Record<string, unknown>;
  if (typeof record.$ref === 'string' && record.$ref.startsWith(REF_PREFIX)) {
    const schemaName = record.$ref.slice(REF_PREFIX.length);
    const mapped = renames.get(schemaName);
    if (mapped) {
      record.$ref = `${REF_PREFIX}${mapped}`;
    }
  }

  for (const value of Object.values(record)) {
    rewriteSchemaRefs(value, renames);
  }
}

/** Combines OpenAPI documents from gateway microservices into one file. */
export function mergeOpenApiSpecs(sources: OpenApiSpecSource[]): MergeOpenApiResult {
  const merged: OpenApiDocument = {
    openapi: '3.0.0',
    info: {
      title: 'Nestlancer API (All Services)',
      description:
        'Aggregated OpenAPI 3 document for all Nestlancer microservices. ' +
        'Generated by the API gateway from per-service /docs-json specs.',
      version: '1.0',
      contact: {
        name: 'Nestlancer API Support',
        url: 'https://nestlancer.com',
      },
    },
    paths: {},
    tags: [],
    servers: [{ url: '/api/v1', description: 'Nestlancer API v1' }],
    components: {
      schemas: {},
      securitySchemes: {},
    },
  };

  const seenPaths = new Map<string, string>();
  const duplicatePaths: MergeOpenApiResult['duplicatePaths'] = [];
  const seenTags = new Set<string>();
  const schemaRenames: SchemaRenameMap = new Map();

  for (const { name, serviceKey, document } of sources) {
    for (const [path, pathItem] of Object.entries(document.paths ?? {})) {
      if (serviceKey !== 'gateway' && !shouldIncludeMicroservicePath(serviceKey, path)) {
        continue;
      }

      const prefixed = prefixOperationIds(pathItem, serviceKey);

      if (!merged.paths![path]) {
        merged.paths![path] = {};
        seenPaths.set(path, name);
      }

      for (const method of HTTP_METHODS) {
        const operation = prefixed[method];
        if (!operation) continue;

        const existingPath = merged.paths![path] as Record<string, unknown>;
        if (existingPath[method]) {
          duplicatePaths.push({
            path,
            method,
            keptFrom: seenPaths.get(path)!,
            skippedFrom: name,
          });
          continue;
        }
        existingPath[method] = operation;
      }
    }

    for (const tag of document.tags ?? []) {
      if (seenTags.has(tag.name)) continue;
      seenTags.add(tag.name);
      merged.tags!.push({
        name: tag.name,
        description: tag.description ?? `${name} service`,
      });
    }

    const components = document.components ?? {};
    mergeComponentSection(
      merged.components!.schemas!,
      components.schemas,
      serviceKey,
      schemaRenames,
    );
    mergeComponentSection(
      merged.components!.securitySchemes!,
      components.securitySchemes,
      serviceKey,
      new Map(),
    );
    mergeComponentSection(
      merged.components!.parameters ?? (merged.components!.parameters = {}),
      components.parameters,
      serviceKey,
      new Map(),
    );
    mergeComponentSection(
      merged.components!.responses ?? (merged.components!.responses = {}),
      components.responses,
      serviceKey,
      new Map(),
    );
  }

  if (schemaRenames.size > 0) {
    rewriteSchemaRefs(merged.paths, schemaRenames);
    rewriteSchemaRefs(merged.components, schemaRenames);
  }

  collectGlobalTagsFromOperations(merged);

  if (merged.tags!.length === 0) delete merged.tags;
  if (Object.keys(merged.components!.schemas!).length === 0) delete merged.components!.schemas;
  if (Object.keys(merged.components!.securitySchemes!).length === 0) {
    delete merged.components!.securitySchemes;
  }

  normalizeOpenApiDocument(merged);

  return { document: merged, duplicatePaths };
}

/** Registers every operation tag in `document.tags` for Spectral `operation-tag-defined`. */
function collectGlobalTagsFromOperations(document: OpenApiDocument): void {
  const tagDescriptions = new Map<string, string>();

  for (const tag of document.tags ?? []) {
    tagDescriptions.set(tag.name, tag.description ?? `${tag.name} API`);
  }

  for (const pathItem of Object.values(document.paths ?? {})) {
    for (const method of HTTP_METHODS) {
      const operation = pathItem[method];
      if (!operation || typeof operation !== 'object' || Array.isArray(operation)) continue;

      const tags = (operation as { tags?: string[] }).tags;
      if (!Array.isArray(tags)) continue;

      for (const name of tags) {
        if (!tagDescriptions.has(name)) {
          tagDescriptions.set(name, `${name} API`);
        }
      }
    }
  }

  if (tagDescriptions.size === 0) return;

  document.tags = [...tagDescriptions.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, description]) => ({ name, description }));
}
