export enum QuoteStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  SENT = 'SENT',
  VIEWED = 'VIEWED',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  REVISED = 'REVISED',
}
