apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-media
  labels:
    app: svc-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-media
  template:
    metadata:
      labels:
        app: svc-media
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: svc-media
          image: ghcr.io/nestlancer/media:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3012
              name: http
          envFrom:
            - secretRef:
                name: nestlancer-secrets
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3012"
          readinessProbe:
            httpGet:
              path: /api/v1/health/ready
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
