apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-notification
  labels:
    app: worker-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-notification
  template:
    metadata:
      labels:
        app: worker-notification
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: worker-notification
          image: ghcr.io/nestlancer/notification-worker:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: nestlancer-secrets
          env:
            - name: NODE_ENV
              value: production
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
