import { Test, TestingModule } from '@nestjs/testing';
import { TotpService } from '../../src/totp.service';

describe('TotpService', () => {
  let service: TotpService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [TotpService],
    }).compile();

    service = module.get<TotpService>(TotpService);
  });

  it('should generate a secret and otpauthUrl', () => {
    const { secret, otpauthUrl } = service.generateSecret();
    expect(secret).toBeDefined();
    expect(otpauthUrl).toContain(secret);
    expect(otpauthUrl).toContain('otpauth://totp/Nestlancer');
  });

  it('should verify a valid token', () => {
    service.generateSecret();
    // We can't easily generate a real token without duplicating the logic
    // but we can test the timingSafeCompare and the structure.
    // For a real test, we'd need to mock Date.now() or use a known secret/time.

    // Let's use a fixed time and secret to test
    const fixedSecret = '48656c6c6f21deadbeef'; // hex for "Hello!..."
    const mockDate = new Date('2023-01-01T00:00:00Z').getTime();
    jest.spyOn(Date, 'now').mockReturnValue(mockDate);

    // The token generated by the service at this time for this secret
    const token = (service as any).generateToken(fixedSecret, Math.floor(mockDate / 1000 / 30));
    const isValid = service.verifyToken(fixedSecret, token);

    expect(isValid).toBe(true);
    jest.restoreAllMocks();
  });

  it('should generate backup codes', () => {
    const codes = service.generateBackupCodes(5);
    expect(codes).toHaveLength(5);
    expect(codes[0]).toMatch(/^[A-F0-9]{4}-[A-F0-9]{4}$/);
  });
});
