/** Canonical in-app notification type strings (API docs + audit extensions). */
export const NotificationEventType = {
  REQUEST_SUBMITTED: 'request.submitted',
  REQUEST_STATUS_CHANGED: 'request.statusChanged',
  REQUEST_ASSIGNED: 'request.assigned',
  QUOTE_RECEIVED: 'quote.received',
  QUOTE_REVISED: 'quote.revised',
  QUOTE_ACCEPTED: 'quote.accepted',
  QUOTE_DECLINED: 'quote.declined',
  QUOTE_CHANGES_REQUESTED: 'quote.changesRequested',
  PAYMENT_DUE: 'payment.due',
  PAYMENT_RECEIVED: 'payment.received',
  PAYMENT_FAILED: 'payment.failed',
  PAYMENT_REFUNDED: 'payment.refunded',
  MESSAGE_NEW: 'message.new',
  MESSAGE_MENTIONED: 'message.mentioned',
  MESSAGE_GROUP_ADDED: 'message.groupAdded',
  MESSAGE_FLAGGED: 'message.flagged',
  CONTACT_INQUIRY: 'contact.inquiry',
  CONTACT_REPLIED: 'contact.replied',
  COMMENT_PENDING: 'comment.pending',
  COMMENT_REPORTED: 'comment.reported',
  REVISION_REQUESTED: 'revision.requested',
  REVISION_COMPLETED: 'revision.completed',
  PROJECT_STATUS_CHANGED: 'project.statusChanged',
  PROJECT_COMPLETED: 'project.completed',
  PROJECT_CREATED: 'project.created',
  MILESTONE_COMPLETED: 'milestone.completed',
  PAYMENT_DISPUTE_OPENED: 'payment.disputeOpened',
  PAYMENT_DISPUTE_RESOLVED: 'payment.disputeResolved',
  PAYMENT_MANUAL_RECORDED: 'payment.manualRecorded',
  PAYMENT_PENDING_VERIFICATION: 'payment.pendingVerification',
  PAYMENT_TRANSFER_APPROVED: 'payment.transferApproved',
  PAYMENT_TRANSFER_REJECTED: 'payment.transferRejected',
  PROJECT_DEADLINE_EXTENDED: 'project.deadlineExtended',
  PROJECT_DUPLICATION_READY: 'project.duplicationReady',
  PROJECT_REVISION_REQUESTED: 'project.revisionRequested',
  FEEDBACK_SUBMITTED: 'feedback.submitted',
  EXPORT_READY: 'export.ready',
  DOCUMENT_READY: 'document.ready',
  DELIVERABLE_READY: 'deliverable.ready',
  PROGRESS_ENTRY_CREATED: 'progress.entryCreated',
  QUOTE_EXPIRING: 'quote.expiring',
  QUOTE_EXPIRED: 'quote.expired',
  MEDIA_QUARANTINED: 'media.quarantined',
  MEDIA_RELEASED: 'media.released',
  ACCOUNT_FORCE_PASSWORD_RESET: 'account.forcePasswordReset',
  ACCOUNT_PASSWORD_RESET: 'account.passwordReset',
  ACCOUNT_SUSPENDED: 'account.suspended',
  ACCOUNT_DELETED: 'account.deleted',
  ACCOUNT_RESTORED: 'account.restored',
  ACCOUNT_ROLE_CHANGED: 'account.roleChanged',
  ACCOUNT_DELETION_SCHEDULED: 'account.deletionScheduled',
  ACCOUNT_DELETION_CANCELLED: 'account.deletionCancelled',
  SECURITY_PASSWORD_CHANGED: 'security.passwordChanged',
  WEBHOOK_DELIVERY_FAILED: 'webhook.deliveryFailed',
  MILESTONE_DEEMED_APPROVED: 'milestone.deemedApproved',
  SYSTEM_ANNOUNCEMENT: 'system.announcement',
} as const;

export type NotificationEventTypeValue =
  (typeof NotificationEventType)[keyof typeof NotificationEventType];
