import { IsString, Length } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

/**
 * DTO for validating the first TOTP code during 2FA setup.
 */
export class Verify2FASetupDto {
  @ApiProperty({
    description: 'The 6-digit verification code generated by the authenticator app',
    example: '123456',
    minLength: 6,
    maxLength: 6,
  })
  @IsString()
  @Length(6, 6, { message: 'Code must be exactly 6 digits' })
  code: string;
}
